language: rust
services: docker
sudo: required

before_cache:
  - chmod -R a+r $HOME/.cargo
cache: cargo

env:
  global:
    - CRATE_NAME=mio-timerfd

matrix:
  include:
    - env: TARGET=aarch64-unknown-linux-gnu
    - env: TARGET=arm-unknown-linux-gnueabi
    - env: TARGET=armv7-unknown-linux-gnueabihf
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=i686-unknown-linux-musl
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl

before_install:
  - set -e
  - rustup self update

script:
  # ignore error if it's already installed
  - cargo install cross || true
  - cross test --target $TARGET
